version: "3.7"
services:
  horovod-master:
    build: horovod-docker
    command: mpirun -np 2 -H horovod-worker1:2 -mca plm_rsh_args "-p 12345" python3 keras_mnist_advanced.py
    volumes:
      - ./share/ssh:/root/.ssh
      - ./imagenet:/root/imagenet

  horovod-worker1:
    build: horovod-docker
    command: bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - ./share/ssh:/root/.ssh

  horovod-worker2:
    build: horovod-docker
    command: bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - ./share/ssh:/root/.ssh

