version: "3"
services:
  horovod-master:
    build: horovod-docker
    command: mpirun -np 6 -H horovod-worker1:1,horovod-worker2:1,horovod-worker3:1,horovod-worker4:1,horovod-worker5:1,horovod-worker6:1 -mca plm_rsh_args "-p 12345" python keras_mnist_advanced.py
    volumes:
      - ./share/ssh:/root/.ssh
      - ./imagenet:/root/imagenet

  horovod-worker1:
    build: horovod-docker
    command: bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    volumes:
      - ./share/ssh:/root/.ssh

  horovod-worker2:
    build: horovod-docker
    command: bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    volumes:
      - ./share/ssh:/root/.ssh

  horovod-worker3:
    build: horovod-docker
    command: bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    volumes:
    - ./share/ssh:/root/.ssh

  horovod-worker4:
    build: horovod-docker
    command: bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    volumes:
    - ./share/ssh:/root/.ssh

  horovod-worker5:
    build: horovod-docker
    command: bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    volumes:
    - ./share/ssh:/root/.ssh

  horovod-worker6:
    build: horovod-docker
    command: bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    volumes:
    - ./share/ssh:/root/.ssh
